server:
  port: 7777
  servlet:
    context-path: /yhy/
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # password:  ??????????????????
    timeout: 10000
    database: 0
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 8
        min-idle: 0
